# Copyright (c) 2022-2025, The Isaac Lab Project Developers (https://github.com/isaac-sim/IsaacLab/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Generate project-local VS Code settings for Isaac Lab development.

The script locates the active Isaac Sim installation, reads its configured
``python.analysis.extraPaths``, and combines those paths with every extension
under this project's ``source`` directory. It then writes the resulting paths
and the active Isaac Sim Python interpreter into ``.vscode/settings.json``.

If ``.vscode/launch.json`` does not exist, the script also creates it from the
project template. Generated settings improve editor imports, completion, and
debugging; they do not change the runtime behavior of Parkour Lab.
"""

import argparse
import os
import pathlib
import platform
import re
import sys

PROJECT_DIR = pathlib.Path(__file__).parents[2]
"""Path to the project root containing ``.vscode`` and ``source``."""

try:
    import isaacsim  # noqa: F401

    isaacsim_dir = os.environ.get("ISAAC_PATH", "")
except ModuleNotFoundError as error:
    # Only fall back when ``isaacsim`` itself is absent. A missing dependency
    # inside an installed Isaac Sim package indicates a broken environment and
    # should retain its original traceback instead of being misdiagnosed as a
    # missing installation path.
    if error.name != "isaacsim":
        raise

    # Accept an explicit Isaac Sim path when its Python package is unavailable.
    parser = argparse.ArgumentParser(
        description="Setup the VSCode settings for the project."
    )
    parser.add_argument(
        "--isaac_path",
        type=str,
        required=True,
        help="The absolute path to the Isaac Sim installation.",
    )
    args = parser.parse_args()

    # Resolve and validate the path supplied on the command line.
    isaacsim_dir = args.isaac_path
    if not os.path.exists(isaacsim_dir):
        raise FileNotFoundError(
            f"Could not find the isaac-sim directory: {isaacsim_dir}. Please provide the correct path to the Isaac Sim"
            " installation."
        )
except EOFError:
    print(
        "Unable to trigger EULA acceptance. This is likely due to the script being run in a non-interactive shell."
    )
    print("Please run the script in an interactive shell to accept the EULA.")
    print("Skipping the setup of the VSCode settings...")
    sys.exit(0)

# Fail early when neither package discovery nor the explicit path succeeded.
if not os.path.exists(isaacsim_dir):
    raise FileNotFoundError(
        f"Could not find the isaac-sim directory: {isaacsim_dir}. There are two possible reasons for this:\n\t1. The"
        " Isaac Sim directory does not exist as provided CLI path.\n\t2. The script couldn't import the 'isaacsim'"
        " package. This could be due to the 'isaacsim' package not being installed in the Python"
        " environment.\n\nPlease make sure that the Isaac Sim directory exists or that the 'isaacsim' package is"
        " installed."
    )

ISAACSIM_DIR = isaacsim_dir
"""Path to the resolved Isaac Sim installation."""


def main() -> None:
    """Generate the project settings and an optional launch configuration."""

    # Locate the project-owned VS Code settings template.
    isaaclab_vscode_template_filename = os.path.join(
        PROJECT_DIR, ".vscode", "tools", "settings.template.json"
    )
    if not os.path.exists(isaaclab_vscode_template_filename):
        raise FileNotFoundError(
            f"Could not find the Isaac Lab template settings file: {isaaclab_vscode_template_filename}"
        )

    # Read the template before replacing its machine-specific values.
    with open(isaaclab_vscode_template_filename) as f:
        isaaclab_template_settings = f.read()

    # Insert import-search paths from Isaac Sim and local project extensions.
    isaaclab_settings = _overwrite_python_analysis_extra_paths(
        isaaclab_template_settings
    )

    # Make VS Code use the interpreter associated with this Isaac Sim setup.
    isaaclab_settings = _overwrite_default_python_interpreter(isaaclab_settings)

    # Mark the output as generated and record the source template.
    header_message = (
        "// This file is a template and is automatically generated by the setup_vscode.py script.\n"
        "// Do not edit this file directly.\n"
        "// \n"
        f"// Generated from: {isaaclab_vscode_template_filename}\n"
    )
    isaaclab_settings = header_message + isaaclab_settings

    # Write the fully resolved workspace settings.
    isaaclab_vscode_filename = os.path.join(PROJECT_DIR, ".vscode", "settings.json")
    with open(isaaclab_vscode_filename, "w") as f:
        f.write(isaaclab_settings)

    # Preserve an existing launch configuration; otherwise create the default.
    isaaclab_vscode_launch_filename = os.path.join(
        PROJECT_DIR, ".vscode", "launch.json"
    )
    isaaclab_vscode_template_launch_filename = os.path.join(
        PROJECT_DIR, ".vscode", "tools", "launch.template.json"
    )
    if not os.path.exists(isaaclab_vscode_launch_filename):
        # Read the launch template and give it the generated-file header.
        with open(isaaclab_vscode_template_launch_filename) as f:
            isaaclab_template_launch_settings = f.read()
        header_message = header_message.replace(
            isaaclab_vscode_template_filename, isaaclab_vscode_template_launch_filename
        )
        isaaclab_launch_settings = header_message + isaaclab_template_launch_settings

        # Write the launch configuration only on its initial creation.
        with open(isaaclab_vscode_launch_filename, "w") as f:
            f.write(isaaclab_launch_settings)


def _overwrite_default_python_interpreter(isaaclab_settings: str) -> str:
    """Set the default Python interpreter in the generated VS Code settings.

    The interpreter is derived from the Python executable running this script.
    When that executable belongs to Kit, the path is converted to Isaac Sim's
    platform-specific Python launcher.

    Args:
        isaaclab_settings: Settings template whose interpreter will be replaced.

    Returns:
        The settings string containing the resolved interpreter path.
    """

    # Normalize the executable path for comparisons and JSON output.
    python_exe = os.path.normpath(sys.executable)

    # Prefer Isaac Sim's launcher over Kit's internal Python executable so the
    # interpreter starts with the required environment and source paths.
    if f"kit{os.sep}python{os.sep}bin{os.sep}python" in python_exe:
        # Select the launcher appropriate for the host operating system.
        if platform.system() == "Windows":
            python_exe = python_exe.replace(
                f"kit{os.sep}python{os.sep}bin{os.sep}python3", "python.bat"
            )
        else:
            python_exe = python_exe.replace(
                f"kit{os.sep}python{os.sep}bin{os.sep}python3", "python.sh"
            )

    # Replace the template's interpreter while leaving other settings intact.
    isaaclab_settings = re.sub(
        r"\"python.defaultInterpreterPath\": \".*?\"",
        f'"python.defaultInterpreterPath": "{python_exe}"',
        isaaclab_settings,
        flags=re.DOTALL,
    )
    return isaaclab_settings


def _overwrite_python_analysis_extra_paths(isaaclab_settings: str) -> str:
    """Populate ``python.analysis.extraPaths`` in the generated settings.

    Paths from Isaac Sim's VS Code settings are made relative to this workspace
    and combined with each local extension under ``source``. If the Isaac Sim
    settings file is unavailable, only local extension paths are included.

    Args:
        isaaclab_settings: Settings template whose analysis paths will be replaced.

    Returns:
        The settings string containing the resolved analysis paths.
    """

    # Locate the settings distributed with the resolved Isaac Sim installation.
    isaacsim_vscode_filename = os.path.join(ISAACSIM_DIR, ".vscode", "settings.json")

    # Import paths for Kit extensions are sourced from Isaac Sim when available.
    if os.path.exists(isaacsim_vscode_filename):
        # Read the source settings before extracting its analysis-path array.
        with open(isaacsim_vscode_filename) as f:
            vscode_settings = f.read()

        # Extract the contents of the ``python.analysis.extraPaths`` array.
        settings = re.search(
            r"\"python.analysis.extraPaths\": \[.*?\]",
            vscode_settings,
            flags=re.MULTILINE | re.DOTALL,
        )
        settings = settings.group(0)
        settings = settings.split('"python.analysis.extraPaths": [')[-1]
        settings = settings.split("]")[0]

        # Convert the comma-separated JSON entries into clean path strings.
        path_names = settings.split(",")
        path_names = [path_name.strip().strip('"') for path_name in path_names]
        path_names = [path_name for path_name in path_names if len(path_name) > 0]

        # Express Isaac Sim paths relative to this workspace for portability.
        rel_path = os.path.relpath(ISAACSIM_DIR, PROJECT_DIR)
        path_names = [
            '"${workspaceFolder}/' + rel_path + "/" + path_name + '"'
            for path_name in path_names
        ]
    else:
        path_names = []
        print(
            f"[WARN] Could not find Isaac Sim VSCode settings: {isaacsim_vscode_filename}."
            "\n\tThis will result in missing 'python.analysis.extraPaths' in the VSCode"
            "\n\tsettings, which limits the functionality of the Python language server."
            "\n\tHowever, it does not affect the functionality of the Isaac Lab project."
            "\n\tWe are working on a fix for this issue with the Isaac Sim team."
        )

    # Add local extensions so the language server resolves project imports.
    isaaclab_extensions = os.listdir(os.path.join(PROJECT_DIR, "source"))
    path_names.extend(
        ['"${workspaceFolder}/source/' + ext + '"' for ext in isaaclab_extensions]
    )

    # Format the collected entries as an indented JSON array body.
    path_names = ",\n\t\t".expandtabs(4).join(path_names)

    # Use forward slashes consistently in generated VS Code settings.
    path_names = path_names.replace("\\", "/")

    # Replace only the template's analysis-path array.
    isaaclab_settings = re.sub(
        r"\"python.analysis.extraPaths\": \[.*?\]",
        '"python.analysis.extraPaths": [\n\t\t'.expandtabs(4)
        + path_names
        + "\n\t]".expandtabs(4),
        isaaclab_settings,
        flags=re.DOTALL,
    )
    return isaaclab_settings


if __name__ == "__main__":
    main()
